-- 코드를 작성해주세요
SELECT 
    SUM(SCORE) AS SCORE, 
    HG.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM HR_EMPLOYEES AS HE
INNER JOIN HR_GRADE AS HG
ON HE.EMP_NO = HG.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING HG.YEAR = '2022'
ORDER BY 1 DESC
LIMIT 1;